version: '2'
services:
    mysql:
        image: mariadb:10.1
        expose:
          - '3306'
        ports:
            - '3306:3306'
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./docker-images/mysql/backup/:/var/lib/mysql/backup
        restart: on-failure
        privileged: false
        env_file:
            - docker.env
    nginx:
        image: nginx:1.15
        ports:
          - "80:80"
        restart: on-failure
        volumes:
            - ./docker-images/nginx-extended/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/code
        links:
          - php-fpm
        depends_on:
          - php-fpm
        networks:
          default:
            aliases:
                - test-api
    php-fpm:
        build: ./docker-images/php-extended
        restart: on-failure
        container_name: php-fpm
        ports:
            - '8080:8080'
        expose:
            - 8080
        environment:
          - PHP_IDE_CONFIG=serverName=test-api
        volumes:
            - ./:/code:cached
            - ./docker-images/php-extended/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./docker-images/php-extended/sendmail.ini:/usr/local/etc/php/conf.d/sendmail.ini
            - ./docker-images/php-extended/ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf
            - ./docker-images/php-extended/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        working_dir: /code
        tty: true
        links:
          - redis
          - mysql
        depends_on:
          - redis
          - mysql
    redis:
      image: 'redis'
      ports:
        - '6379:6379'
      volumes:
        - ./data/redis:/data
    pma:
      image: 'phpmyadmin/phpmyadmin:latest'
      ports:
        - '8090:80'
      environment:
        - MYSQL_USER=docker
        - MYSQL_ROOT_PASSWORD=docker
        - PMA_HOST=mysql

    mail:
      image: tophfr/mailcatcher:latest
      ports:
        - 1080:80