index:
  path: /
  controller: App\Controller\Frontend\AuthController::index

registration:
  path: /registration
  controller: App\Controller\Frontend\AuthController::registration

register:
  path: /register
  controller: App\Controller\RegistrationController::index
  methods: POST

gesdinet_jwt_refresh_token:
  path:       /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh

admin:
  resource: routes/admin/admin.yaml
  prefix: /admin

api_login_check:
  path: /api/login_check